FROM ubuntu:20.04
ENV TZ=Europe/Kiev
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt update && apt install -y alsa-base alsa-utils pulseaudio python3 python3-pip python3-gst-1.0 gstreamer1.0-tools gstreamer1.0-nice gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-plugins-good libgstreamer1.0-dev git libglib2.0-dev libgstreamer-plugins-bad1.0-dev libsoup2.4-dev libjson-glib-dev gstreamer1.0-alsa gstreamer1.0-pulseaudio
RUN pip3 install requests websockets nest_asyncio
COPY . .
#ENV GST_DEBUG=*3,webrtc*:9
ENTRYPOINT ["python3","gstwebrtc_caller_callee.py"]
CMD ["dummy"]
#docker build --tag pygstwebrtc .
#xhost local:docker #give docker access rights to xserver
#docker run -it -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY --rm --net=host pygstwebrtc 134 # xserver only support
#audio support see: https://github.com/jessfraz/dockerfiles/issues/85#issuecomment-299431931
#docker run -it -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY --rm --net=host --device /dev/snd -e PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native -v ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native -v ~/.config/pulse/cookie:/root/.config/pulse/cookie --group-add $(getent group audio | cut -d: -f3) pygstwebrtc 134
#xhost -local:docker #remove access rights again
